version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ntaganira1956!
      POSTGRES_DB: event_management_system
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
